name: Project Proposal
description: Suggest an idea for a project
labels: []

body:
  - type: markdown
    attributes:
      value: "# Project proposal"

  - type: textarea
    attributes:
      label: Description
      description: one or two paragraphs describing the idea. Projects should take approximately 3 months to reasonably complete. The projects will 1) build technical skills, increase our number of core contributors, and work on meaningful projects we want to integrate into Qiskit or maintain; 2) Tackle problems that relate to advancing quantum computing. For example, publishing a quantum computing paper, building a successful local community, or increasing diversity.
      value: |
        <!-- example
        QPong
        -->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Deliverables
      description: What's the expected result?
      value: |
        <!-- example
        -->
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Mentors"

  - type: textarea
    attributes:
      label: Mentors details
      description: Please enter mentors' names, GitHub IDs and what they do in the following format.
      value: |
        <!-- example
        - Mentor 1
          - Name: Junye Huang
          - GitHub ID: @HuangJunye
          - What they do: Quantum Developer Advocate and part of Qiskit advocate squad
        - Mentor 2
          - Name: Luciano Bello
          - GitHub ID:@1ucian0
          - What they do: Qiskit core developer
        -->
        - Mentor 1
          - Name:
          - GitHub ID:
          - What they do:
        - Mentor 2
          - Name:
          - GitHub ID:
          - What they do:
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Mentees"

  - type: dropdown
    attributes:
      label: Number of mentees
      description: What is the ideal number of people to work on this project?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
      required: true

  - type: textarea
    attributes:
      label: Type of mentees
      description: What are the profiles of the ideal participants for this idea?
      value: |
        <!-- example
        - Mentee 1
          - Required:
            - Interested in game development
          - Nice to have:
            - Experience in game development
            - Knowledge in quantum information
        - Mentor 2
          - Required:
            - Proficient in Qiskit
          - Nice to have:
            - Experience in Qiskit open source contributions
        -->
        - Mentor 1
          - Required:
            - item 1
          - Nice to have:
            - item 1
        - Mentor 2
          - Required:
            - item 1
          - Nice to have:
            - item 1
    validations:
      required: true