name: GitHub Actions QAMP Issues

run-name: ${{ github.actor }} is using GitHub Actions 🚀

on:
  issues:
    types: [opened]

jobs:
  assign:
    name: Assign QAMP projects to GitHub project
    runs-on: ubuntu-latest
    steps:
      name: Add To GitHub projects
      uses: actions/add-to-project@v0.4.1
      with:
        project-url: https://github.com/orgs/qiskit-advocate/projects/4
        github-token: ${{ secrets.GEMMA_PAT }}
        column-name: Mentor Proposed Projects
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v2
        with:
          labels: |
            from: mentor
            mentee needed
